const fs = require('fs');
let content = fs.readFileSync('defaultPrompts.ts', 'utf-8');

content = content.replace(
  /refineRubricWithContext: \`[\s\S]*?====================\`,/g,
  `refineRubricWithContext: \`Refine and format the user's provided rubric into a quick, plain-spoken bulleted checklist, while ALSO combining it with context from the HOMEWORK TASK and COURSE RESOURCES.\\nWrite with a purely functional, diagnostic efficiency. Eliminate all conversational fluff, academic jargon, and narrative detours. Use structurally precise, logically sequential, and direct language. Deliver raw cause-and-effect information in the shortest path possible using plain-spoken, unambiguous terms.\\nCRITICAL RULE 1: Anchor the rubric to the specific subject matter! Use the specific topics from the COURSE RESOURCES to form the rubric items (e.g., require them to discuss specific frameworks, language types, or workflows mentioned in the text).\\nCRITICAL RULE 2: Write in the 'ecliptic style': purely functional, direct, and action-oriented. Do NOT use academic jargon. Use plain-spoken English. NEVER assume the student actually performed a physical lab/project unless the homework explicitly says so; ask them to explain how a process works step-by-step rather than asking about their personal experience.\\nCRITICAL RULE 3: YOU MUST PRESERVE EVERY SPECIFIC REQUIREMENT FROM THE USER'S ORIGINAL RUBRIC. If the user asks for a specific length (e.g., '10 sentences'), a specific format, or a specific constraint, you MUST include it in the final output. Do not drop the user's constraints!\\nCRITICAL RULE 4: Consolidate the output into a MAXIMUM of 4 to 5 bullet points total. Merge related concepts to keep it short. Do NOT exceed 5 bullets.\\nCRITICAL RULE 5: Output ONLY the bullets. No intro or outro.\\n\\n=== USER'S ORIGINAL RUBRIC REQUIREMENTS ===\\n{{BASE_RUBRIC}}\\n=======================================\\n\\n=== COURSE RESOURCES (For Context & Topics) ===\\n{{RESOURCES_TEXT}}\\n======================\\n\\n=== HOMEWORK TASK (The Actual Assignment) ===\\n{{CONTENT}}\\n====================\`,`
);

content = content.replace(
  /refineRubricWithoutContext: \`[\s\S]*?=============\`,/g,
  `refineRubricWithoutContext: \`Format this text into a quick, plain-spoken bulleted checklist. \\nWrite with a purely functional, diagnostic efficiency. Eliminate all conversational fluff, academic jargon, and narrative detours. Use structurally precise, logically sequential, and direct language. Deliver raw cause-and-effect information in the shortest path possible using plain-spoken, unambiguous terms.\\nCRITICAL RULE 1: YOU MUST PRESERVE EVERY SPECIFIC REQUIREMENT FROM THE TEXT. If the user asks for a specific length (e.g., '10 sentences'), format, or constraint, you MUST include it.\\nCRITICAL RULE 2: Don't give away the actual answers. Just list what's needed for credit.\\nOutput ONLY the bullets. No intro or outro.\\n\\n=== TEXT ===\\n{{BASE_RUBRIC}}\\n=============\`,`
);

fs.writeFileSync('defaultPrompts.ts', content);
